from chess_visualisation import Chesspiece
from chess_visualisation import ChessBoard

b = ChessBoard()
b.update("e4")
b.update("e5")
b.update("bc4")
b.update("nf6")
print(str(b))
b.update("nf3")
print(str(b))
b.update("g6")
b.update("O-O")
print(str(b))

c = ChessBoard()
c.update("e4")
c.update("nf6")
c.update("nf3")
c.update("ng8")
c.update("ng5")
print(c.return_available_moves())
c.update("nf6")
c.update("nxh7")
c.update("ng8")
c.update("nf6")
array = c.return_available_moves()
print(array)

print("testing checkmate!")
d = ChessBoard()
d.update("e4")
d.update("e5")
print(str(d))
d.update("Bc4")
d.update("nf6")
d.update("qf3")
d.update("ng8")
d.update("qxf7")
print(d.return_available_moves())
e = ChessBoard()
e.update("h4")
e.update("e5")
print("testing if weird rook moves are available")
print(e.return_available_moves())

f = ChessBoard()
f.update("h4")
f.update("g5")
f.update("hxg5")
f.update("h6")
f.update("gxh6")
f.update("nf6")
f.update("h7")
f.update("ng8")
print(str(f))
f.update("hxg8=Q")
print(str(f))
